export const images = {
  homeAbout: '/images/home-about.webp',
  zakelijkHero: '/images/DSC_1082.webp',
  aboutStory: '/images/DSC_0839.webp',
  serviceInterieur: '/images/service-interieur.webp',
  serviceExterieur: '/images/service-exterieur.webp',
  serviceFull: '/images/service-full.webp',
  servicePolieren: '/images/service-polieren.webp',
  serviceMoto: '/images/service-moto.png',
  serviceCoating: '/images/DSC_1710.webp',
  qualityProducts: '/images/quality-products.webp',
  aandachtDetail: '/images/DSC_1082.webp',
  teamRenzo: '/images/DSC_0735.webp',
  teamThibo: '/images/DSC_1080.webp',
}
